version: '3.8'

services:

  server:
    container_name: server
    build:
      context: server
      dockerfile: Dockerfile
      target: development
    env_file: 'server/.env'
    networks:
      - appnet
    depends_on:
      - database
      - mongo-express
    ports:
      - '3000:3000'
    command: yarn run start:dev

  database:
    container_name: database
    image: mongo
    restart: always
    networks:
      - appnet
    env_file: 'server/.env'
    volumes:
      - ./db_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}

  mongo-express:
      container_name: mongo-express
      image: mongo-express
      restart: always
      ports:
        - '8081:8081'
      networks:
        - appnet
      env_file: 'server/.env'
      environment:
        ME_CONFIG_MONGODB_ADMINUSERNAME: ${ME_CONFIG_MONGODB_ADMINUSERNAME}
        ME_CONFIG_MONGODB_ADMINPASSWORD: ${ME_CONFIG_MONGODB_ADMINPASSWORD}
        ME_CONFIG_MONGODB_URL: ${ME_CONFIG_MONGODB_URL}



networks:
  appnet:

volumes:
  db_val:
    driver: local
  app:
    driver: local
